language: node_js
node_js:
  - 'stable'
install: npm install
services:
  - postgresql
before_script:
  - psql -c 'create database DATABASE_URL_TEST;' -U postgres
script: npm test
after_success: npm run coverage
